apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: helloworld-app-1
        image: docker.io/kusolank812/helloworld-app:1.0-amd64 
        # resources:
        #   limits:
        #     cpu: 300m
        #     memory: 500Mi
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi 
        ports:
        - containerPort: 9982 # Adjust the port as per your application's configuration

  

